name: custom_hue
description: "Philips Hue BLE Control App"
publish_to: 'none'
version: 1.1.1+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_reactive_ble: ^5.3.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  android_alarm_manager_plus: ^5.0.0
  flutter_colorpicker: ^1.1.0
  permission_handler: ^12.0.0
  uuid: ^4.5.1
  intl: ^0.20.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
